// Code generated by optiongen. DO NOT EDIT.
// optiongen: github.com/timestee/optiongen

package checkup

import (
	"context"

	"github.com/sandwich-go/checkup/protocol/gen/golang/common"
	"github.com/sandwich-go/checkup/protocol/gen/golang/internal_command"
)

// Options should use NewOptions to initialize it
type Options struct {
	DevopsCheckup func(ctx context.Context) *internal_command.CmdCheckup
	Codec         Codec
	OnError       func(err error)
}

// NewOptions new Options
func NewOptions(opts ...Option) *Options {
	cc := newDefaultOptions()
	for _, opt := range opts {
		opt(cc)
	}
	if watchDogOptions != nil {
		watchDogOptions(cc)
	}
	return cc
}

// ApplyOption apply multiple new option
func (cc *Options) ApplyOption(opts ...Option) {
	for _, opt := range opts {
		opt(cc)
	}
}

// Option option func
type Option func(cc *Options)

// WithDevopsCheckup option func for filed DevopsCheckup
func WithDevopsCheckup(v func(ctx context.Context) *internal_command.CmdCheckup) Option {
	return func(cc *Options) {
		cc.DevopsCheckup = v
	}
}

// WithCodec option func for filed Codec
func WithCodec(v Codec) Option {
	return func(cc *Options) {
		cc.Codec = v
	}
}

// WithOnError option func for filed OnError
func WithOnError(v func(err error)) Option {
	return func(cc *Options) {
		cc.OnError = v
	}
}

// InstallOptionsWatchDog the installed func will called when NewOptions  called
func InstallOptionsWatchDog(dog func(cc *Options)) { watchDogOptions = dog }

// watchDogOptions global watch dog
var watchDogOptions func(cc *Options)

// newDefaultOptions new default Options
func newDefaultOptions() *Options {
	cc := &Options{}

	for _, opt := range [...]Option{
		WithDevopsCheckup(func(ctx context.Context) *internal_command.CmdCheckup {
			return &internal_command.CmdCheckup{Code: common.ErrorCode_OK.NumberInt32(), Message: "default ok"}
		}),
		WithCodec(jsonCodec{}),
		WithOnError(func(err error) {
		}),
	} {
		opt(cc)
	}

	return cc
}

// all getter func
func (cc *Options) GetDevopsCheckup() func(ctx context.Context) *internal_command.CmdCheckup {
	return cc.DevopsCheckup
}
func (cc *Options) GetCodec() Codec             { return cc.Codec }
func (cc *Options) GetOnError() func(err error) { return cc.OnError }

// OptionsVisitor visitor interface for Options
type OptionsVisitor interface {
	GetDevopsCheckup() func(ctx context.Context) *internal_command.CmdCheckup
	GetCodec() Codec
	GetOnError() func(err error)
}

// OptionsInterface visitor + ApplyOption interface for Options
type OptionsInterface interface {
	OptionsVisitor
	ApplyOption(...Option)
}
