// ======================================
// ENGINE LEVEL PACKET. DO NOT EDIT.
// ======================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.4
// source: netutils/packet.proto

package netutils

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RawPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version    int32 `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	SequenceID int32 `protobuf:"varint,2,opt,name=SequenceID,proto3" json:"SequenceID,omitempty"`
	// metadata is a mapping from metadata key to value.
	Metadata []string `protobuf:"bytes,19,rep,name=metadata,proto3" json:"metadata,omitempty"`
	// default using queue mode, rawAny should be provided at least one
	RawAny []*RawAny `protobuf:"bytes,20,rep,name=rawAny,proto3" json:"rawAny,omitempty"`
	// reserved
	ReservedInt1   int32  `protobuf:"varint,30,opt,name=ReservedInt1,proto3" json:"ReservedInt1,omitempty"`
	ReservedInt2   int32  `protobuf:"varint,31,opt,name=ReservedInt2,proto3" json:"ReservedInt2,omitempty"`
	ReservedStr1   string `protobuf:"bytes,32,opt,name=ReservedStr1,proto3" json:"ReservedStr1,omitempty"`
	ReservedStr2   string `protobuf:"bytes,33,opt,name=ReservedStr2,proto3" json:"ReservedStr2,omitempty"`
	ReservedBytes1 []byte `protobuf:"bytes,34,opt,name=ReservedBytes1,proto3" json:"ReservedBytes1,omitempty"`
	ReservedBytes2 []byte `protobuf:"bytes,35,opt,name=ReservedBytes2,proto3" json:"ReservedBytes2,omitempty"`
}

func (x *RawPacket) Reset() {
	*x = RawPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netutils_packet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawPacket) ProtoMessage() {}

func (x *RawPacket) ProtoReflect() protoreflect.Message {
	mi := &file_netutils_packet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawPacket.ProtoReflect.Descriptor instead.
func (*RawPacket) Descriptor() ([]byte, []int) {
	return file_netutils_packet_proto_rawDescGZIP(), []int{0}
}

func (x *RawPacket) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RawPacket) GetSequenceID() int32 {
	if x != nil {
		return x.SequenceID
	}
	return 0
}

func (x *RawPacket) GetMetadata() []string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RawPacket) GetRawAny() []*RawAny {
	if x != nil {
		return x.RawAny
	}
	return nil
}

func (x *RawPacket) GetReservedInt1() int32 {
	if x != nil {
		return x.ReservedInt1
	}
	return 0
}

func (x *RawPacket) GetReservedInt2() int32 {
	if x != nil {
		return x.ReservedInt2
	}
	return 0
}

func (x *RawPacket) GetReservedStr1() string {
	if x != nil {
		return x.ReservedStr1
	}
	return ""
}

func (x *RawPacket) GetReservedStr2() string {
	if x != nil {
		return x.ReservedStr2
	}
	return ""
}

func (x *RawPacket) GetReservedBytes1() []byte {
	if x != nil {
		return x.ReservedBytes1
	}
	return nil
}

func (x *RawPacket) GetReservedBytes2() []byte {
	if x != nil {
		return x.ReservedBytes2
	}
	return nil
}

type RawAny struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//fullname of proto or user defined(need mapping to proto) for de/serialization
	Uri string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	//bytes array for sub-proto message
	Raw []byte `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
	// uuid of each request, 1: for debug trace, 2: as request number under http
	// server push and one way request will ignore passThrough
	PassThrough string `protobuf:"bytes,3,opt,name=passThrough,proto3" json:"passThrough,omitempty"`
}

func (x *RawAny) Reset() {
	*x = RawAny{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netutils_packet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawAny) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawAny) ProtoMessage() {}

func (x *RawAny) ProtoReflect() protoreflect.Message {
	mi := &file_netutils_packet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawAny.ProtoReflect.Descriptor instead.
func (*RawAny) Descriptor() ([]byte, []int) {
	return file_netutils_packet_proto_rawDescGZIP(), []int{1}
}

func (x *RawAny) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *RawAny) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *RawAny) GetPassThrough() string {
	if x != nil {
		return x.PassThrough
	}
	return ""
}

var File_netutils_packet_proto protoreflect.FileDescriptor

var file_netutils_packet_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6e, 0x65, 0x74, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6e, 0x65, 0x74, 0x75, 0x74, 0x69, 0x6c,
	0x73, 0x22, 0xeb, 0x02, 0x0a, 0x09, 0x52, 0x61, 0x77, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x53,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x13, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x28, 0x0a, 0x06, 0x72, 0x61, 0x77, 0x41, 0x6e, 0x79, 0x18,
	0x14, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6e, 0x65, 0x74, 0x75, 0x74, 0x69, 0x6c, 0x73,
	0x2e, 0x52, 0x61, 0x77, 0x41, 0x6e, 0x79, 0x52, 0x06, 0x72, 0x61, 0x77, 0x41, 0x6e, 0x79, 0x12,
	0x22, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x49, 0x6e, 0x74, 0x31, 0x18,
	0x1e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x49,
	0x6e, 0x74, 0x31, 0x12, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x49,
	0x6e, 0x74, 0x32, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x52, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x64, 0x49, 0x6e, 0x74, 0x32, 0x12, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x64, 0x53, 0x74, 0x72, 0x31, 0x18, 0x20, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x52,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x53, 0x74, 0x72, 0x31, 0x12, 0x22, 0x0a, 0x0c, 0x52,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x53, 0x74, 0x72, 0x32, 0x18, 0x21, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x53, 0x74, 0x72, 0x32, 0x12,
	0x26, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73,
	0x31, 0x18, 0x22, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x31, 0x12, 0x26, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x32, 0x18, 0x23, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0e, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x32, 0x22,
	0x4e, 0x0a, 0x06, 0x52, 0x61, 0x77, 0x41, 0x6e, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x10, 0x0a, 0x03, 0x72,
	0x61, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x61, 0x77, 0x12, 0x20, 0x0a,
	0x0b, 0x70, 0x61, 0x73, 0x73, 0x54, 0x68, 0x72, 0x6f, 0x75, 0x67, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x73, 0x73, 0x54, 0x68, 0x72, 0x6f, 0x75, 0x67, 0x68, 0x42,
	0x3d, 0x5a, 0x30, 0x62, 0x69, 0x74, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x6f, 0x72, 0x67,
	0x2f, 0x66, 0x75, 0x6e, 0x70, 0x6c, 0x75, 0x73, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x63,
	0x68, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x6e, 0x65, 0x74, 0x75, 0x74,
	0x69, 0x6c, 0x73, 0xaa, 0x02, 0x08, 0x6e, 0x65, 0x74, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_netutils_packet_proto_rawDescOnce sync.Once
	file_netutils_packet_proto_rawDescData = file_netutils_packet_proto_rawDesc
)

func file_netutils_packet_proto_rawDescGZIP() []byte {
	file_netutils_packet_proto_rawDescOnce.Do(func() {
		file_netutils_packet_proto_rawDescData = protoimpl.X.CompressGZIP(file_netutils_packet_proto_rawDescData)
	})
	return file_netutils_packet_proto_rawDescData
}

var file_netutils_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_netutils_packet_proto_goTypes = []interface{}{
	(*RawPacket)(nil), // 0: netutils.RawPacket
	(*RawAny)(nil),    // 1: netutils.RawAny
}
var file_netutils_packet_proto_depIdxs = []int32{
	1, // 0: netutils.RawPacket.rawAny:type_name -> netutils.RawAny
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_netutils_packet_proto_init() }
func file_netutils_packet_proto_init() {
	if File_netutils_packet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_netutils_packet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_netutils_packet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawAny); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_netutils_packet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_netutils_packet_proto_goTypes,
		DependencyIndexes: file_netutils_packet_proto_depIdxs,
		MessageInfos:      file_netutils_packet_proto_msgTypes,
	}.Build()
	File_netutils_packet_proto = out.File
	file_netutils_packet_proto_rawDesc = nil
	file_netutils_packet_proto_goTypes = nil
	file_netutils_packet_proto_depIdxs = nil
}
